import type { NextPage, NextPageContext } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import Main from './download/_main'
import t from './languages'

const Home: NextPage = () => {
    return (
        <div className={styles.container}>
            <Head>
                <title>shinnku App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <Link href="/download">shinnku.com!</Link>
                </h1>
            </main>
        </div>
    )
}


const Download: NextPage = (props: {}) => {
    const language: string = (props as any).language
    return (
      <div className={styles.container}>
        <Head>
          <meta charSet="UTF-8" />
          <title>{t("Title", language)}</title>
          <link rel="icon" type="image/svg+xml" href="/favicon.ico" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <meta name="description" content="shinnku's galgame site" />
          <link rel="manifest" href="/manifest.json" />
        </Head>
  
        <main className={styles.main}>
          <Main isMobile={(props as any).isMobile} lang={language} />
        </main>
  
      </div>
    )
  }

Download.getInitialProps = addDefaultProp

Home.getInitialProps = addDefaultProp

export async function addDefaultProp(ctx: NextPageContext) {
    let language = ctx.req?.headers['accept-language'] || "en,"
    language = language.substring(0, language.indexOf(","))
    console.log(language)
    const isMobileView = ((ctx.req
        ? ctx.req.headers['user-agent']
        : navigator.userAgent) as string).match(
            /Android|BlackBerry|iPhone|iPad|iPod|Opera Mini|IEMobile|WPDesktop/i
        )

    //Returning the isMobileView as a prop to the component for further use.
    const isMobile = Boolean(isMobileView)
    console.log(`isMobile is ${isMobile}`)
    return {
        isMobile: isMobile,
        language: language,
    }
}

export default Download
