import { ColorModeScript, theme } from '@chakra-ui/react'
import type { NextPage, NextPageContext } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import App from '../components'

const Home: NextPage = (props: Record<string, never>) => {
  const language: string = (props as any).language
  const isMobile: boolean = (props as any).isMobile
  return (
    <div className={styles.container}>
      <Head>
        <title>shinnku App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <App lang={language} isMobile={isMobile} />
      </main>
    </div>
  )
}

Home.getInitialProps = addDefaultProp

export async function addDefaultProp(ctx: NextPageContext) {
  let language = ctx.req?.headers['accept-language'] || 'en,'
  language = language.substring(0, language.indexOf(','))
  console.log(language)
  const isMobileView = (
    (ctx.req ? ctx.req.headers['user-agent'] : navigator.userAgent) as string
  ).match(/Android|BlackBerry|iPhone|iPad|iPod|Opera Mini|IEMobile|WPDesktop/i)
  const isMobile = Boolean(isMobileView)
  console.log(`isMobile is ${isMobile}`)
  return {
    isMobile: isMobile,
    language: language,
  }
}

export default Home
