# generated by Claude.ai
import re

with open("a.txt", "r") as file:
    lines = file.readlines()

pattern = re.compile(r".*file not in webdav root.*")

with open("b.txt", "w") as output_file:
    for line in lines:
        if pattern.match(line):
            output_file.write(line)


with open("b.txt", "r") as file:
    lines = file.readlines()

with open("c.txt", "w") as output_file:
    for line in lines:
        file_path = line.split(": file not in webdav root")[0].split(": ")[1].strip()
        new_line = f"{file_path}\n"
        output_file.write(new_line)
