import { ColorModeScript, theme } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import App from '../../components'
import { addDefaultProp } from '../../utils/addDefaultProp'

const Home: NextPage = (props: Record<string, never>) => {
  const language: string = (props as any).language
  const isMobile: boolean = (props as any).isMobile
  return (
    <div className={styles.container}>
      <Head>
        <title>shinnku App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <App lang={language} isMobile={isMobile} />
      </main>
    </div>
  )
}

Home.getInitialProps = addDefaultProp

export default Home
